### ISSUE TITLE
Restructure the organization README

### ISSUE THREAD

**Issue by advaith-unnikrishnan** [dscmbcet/.github#1]
Please include the following details in the README file:
- Brief description about GDSC MBCET (with logo)
- Link to social handles
- Open source projects **_open for contribution_**

**Comment by JCustin** [comment]
Hey Advaith, I'd love to help out. Can you provide me all the active social handles for GDSC MBCET?

**Comment by advaith-unnikrishnan** [comment]
Hey @JCustin we appreciate your effort to contribute to the project but the issue is already assigned to @mak626

**Comment by mak626** [comment]
@advaith-unnikrishnan #2 should fix it
